[tool.black]
line-length = 119
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 119

[tool.flake8]
max-line-length = 119
extend-ignore = ["E203", "W503"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "sanisettes_project.settings"
python_files = "tests.py test_*.py *_tests.py"
addopts = "--cov=sanisettes_project --cov=locator --cov-report=html --no-header"
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
    "unit: marks tests as unit tests",
    "e2e: marks tests as end-to-end tests"
]

[tool.coverage.run]
omit = ["*/__init__.py", "*/migrations/*"]

[tool.coverage.report]
show_missing = true
