services:
  - type: web
    name: sanisettes-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - fromDatabase:
          name: sanisettes-db
          property: user
        key: POSTGRES_USER
      - fromDatabase:
          name: sanisettes-db
          property: password
        key: POSTGRES_PASSWORD
      - fromDatabase:
          name: sanisettes-db
          property: database
        key: POSTGRES_DB
      - fromDatabase:
          name: sanisettes-db
          property: host
        key: POSTGRES_HOST
      - fromDatabase:
          name: sanisettes-db
          property: port
        key: POSTGRES_PORT

databases:
  - name: sanisettes-db
    plan: free
